event_code = {
    1: 'Inquiry Complete',
    2: 'Inquiry Result',
    3: 'Connection Complete',
    4: 'Connection Request',
    5: 'Disconnection Complete',
    6: 'Authentication Complete',
    7: 'Remote Name Request Complete',
    8: 'Encryption Change',
    9: 'Change Connection Link Key Complete',
    10: 'Master Link Key Complete',
    11: 'Read Remote Supported Features Complete',
    12: 'Read Remote Version Information Complete',
    13: 'QoS Setup Complete',
    14: 'Command Complete',
    15: 'Command Status',
    16: 'Hardware Error',
    17: 'Flush Occurred',
    18: 'Role Change',
    19: 'Number Of Completed Packets',
    20: 'Mode Change',
    21: 'Return Link Keys',
    22: 'PIN Code Request',
    23: 'Link Key Request',
    24: 'Link Key Notification',
    25: 'Loopback Command',
    26: 'Data Buffer Overflow',
    27: 'Max Slots Change',
    28: 'Read Clock Offset Complete',
    29: 'Connection Packet Type Changed',
    30: 'QoS Violation',
    32: 'Page Scan Repetition Mode Change',
    33: 'Flow Specification Complete',
    34: 'Inquiry Result with RSSI',
    35: 'Read Remote Extended Features Complete',
    44: 'Synchronous Connection Complete',
    45: 'Synchronous Connection Changed',
    46: 'Sniff Subrating',
    47: 'Extended Inquiry Result',
    48: 'Encryption Key Refresh Complete',
    49: 'IO Capability Request',
    50: 'IO Capability Response',
    51: 'User Confirmation Request',
    52: 'User Passkey Request',
    53: 'Remote OOB Data Request',
    54: 'Simple Pairing Complete',
    56: 'Link Supervision Timeout Changed',
    57: 'Enhanced Flush Complete',
    59: 'User Passkey Notification',
    60: 'Keypress Notification',
    61: 'Remote Host Supported Features Notification',
    62: 'LE',                                   # LE, MUST PROCESS SUBEVENT_CODE...
    64: 'Physical Link Complete',
    65: 'Channel Selected',
    66: 'Disconnection Physical Link Complete',
    67: 'Physical Link Loss Early Warning',
    68: 'Physical Link Recovery',
    69: 'Logical Link Complete',
    70: 'Disconnection Logical Link Complete',
    71: 'Flow Spec Modify Complete',
    72: 'Number Of Completed Data Blocks',
    73: 'AMP Start Test',
    74: 'AMP Test End',
    75: 'AMP Receiver Report',
    76: 'Short_ Range_ Mode_ Change_Complete',
    77: 'AMP_ Status_ Change',
    78: 'Triggered Clock Capture',
    79: 'Synchronization Train Complete',
    80: 'Synchronization Train Received',
    81: 'Connectionless Slave Broadcast Receive',
    82: 'Connectionless Slave Broadcast Timeout',
    83: 'Truncated Page Complete',
    84: 'Slave Page Response Timeout',
    85: 'Connectionless Slave Broadcast Channel Map Change',
    86: 'Inquiry Response Notification',
    87: 'Authenticated Payload Timeout Expired',
    88: 'SAMStatusChange'
}

